### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by RuchirChawdhry** [MinaOTP/MinaOTP-MAC#2]
The icon doesn't show up properly in Mojave's Dark Mode. 

![Screenshot 2019-09-17 at 13 48 06](https://user-images.githubusercontent.com/4688811/65025313-1f78c700-d954-11e9-9775-1b38b927def7.png)
![Screenshot 2019-09-17 at 13 48 36](https://user-images.githubusercontent.com/4688811/65025316-21db2100-d954-11e9-9b08-e9e6012a25ea.png)

**Comment by vibeinging** [comment]
OK   i will  fix it.  thank issues

**Comment by Schlaubischlump** [comment]
Should be fixed in Pull Request #3
