### ISSUE TITLE
License infringement ?

### ISSUE THREAD

**Issue by Schlaubischlump** [MinaOTP/MinaOTP-MAC#4]
This [application](https://apps.apple.com/de/app/otp-authenticator/id1477326354?l=en&mt=12) looks a lot like yours. If this person used your code without your knowledge, this is illegal because you did not include a license file in your project. In this case you should be able to request the removal of the application from the App Store.

**Comment by vibeinging** [comment]
very  very  very  very thank you！

**Comment by Schlaubischlump** [comment]
No problem, great project !

**Comment by vibeinging** [comment]
@Schlaubischlump Hey,bro, he will remove the App from Appstore. He will release "OTP Authenticator 2” application and its will not contain any part of my code.  Thanks for your issues.

**Comment by Schlaubischlump** [comment]
Great that the issue could be resolved ! 

You should think about adding a license file to your project. Technically it is illegal to even fork and contribute to your project if you not include any license file. 

Maybe a GPLv3 license? This makes your app free and forces everyone to opensource there changes under GPLv3 as well. 
Last time I checked GPLv3 was incompatible with the AppStore, so only you would be able to dual-license and publish the app. 

Most likely you don‘t want and MIT license, because in this case everyone could publish your app, if he includes your license file and thereby credits you for your work. 

I‘m not an expert regarding licenses. Maybe you find some time to find a license which suits your needs.

**Comment by vibeinging** [comment]
GPLv3 has been added~. I thought it was a failure app. Is too small. Thank you for giving it new life.

**Comment by Schlaubischlump** [comment]
Definitely not a failure app ! I really like and use it often. 

If get macOS Big Sur up and running and find some free time I will try to update the app to the new interface (if any changes are required).
